"""Host-only, bounded Codex app-server stdio protocol primitive.

Trusted host code supplies argv, cwd, the COMPLETE child environment and fixed
callback. No loader, shell, credential adoption, production registry, sandbox
qualification or workflow is supplied. Method params/results need independent
parent validation. Notification names follow public CLI 0.159.3 generated schema;
accepting a notification never authorizes an action. Payloads stay in memory and
are never copied into diagnostics. Stderr is discarded.

A callback must itself be bounded trusted code: this synchronous primitive cannot
interrupt Python callbacks. Any protocol/IO/callback uncertainty latches UNKNOWN;
there is no retry, relaunch, kill, or descendant-stop claim. close() only closes
pipes and observes the direct child for a bounded interval.
"""
from collections import deque
from dataclasses import dataclass
import json
import math
import os
import selectors
import subprocess
import time


CLIENT_METHODS = frozenset({"initialize", "thread/start", "turn/start",
    "turn/interrupt", "thread/read", "model/list", "account/read", "config/read",
    "configRequirements/read", "experimentalFeature/list", "mcpServerStatus/list"})
# Public ServerNotification.json, generated by Codex CLI 0.159.3.
NOTIFICATION_METHODS = frozenset(('error',
 'thread/started',
 'thread/status/changed',
 'thread/archived',
 'thread/deleted',
 'thread/unarchived',
 'thread/closed',
 'thread/reverted',
 'skills/changed',
 'thread/name/updated',
 'thread/attachment/updated',
 'thread/goal/updated',
 'thread/goal/cleared',
 'thread/queue/changed',
 'project/changed',
 'thread/project/updated',
 'thread/environment/connected',
 'thread/environment/disconnected',
 'thread/settings/updated',
 'thread/tokenUsage/updated',
 'turn/started',
 'hook/started',
 'turn/completed',
 'hook/completed',
 'turn/diff/updated',
 'turn/plan/updated',
 'item/started',
 'item/autoApprovalReview/started',
 'item/autoApprovalReview/completed',
 'autoApprovalReview/strictReviewRequired',
 'item/completed',
 'item/agentMessage/delta',
 'item/plan/delta',
 'command/exec/outputDelta',
 'process/outputDelta',
 'process/exited',
 'item/commandExecution/outputDelta',
 'item/commandExecution/terminalInteraction',
 'item/fileChange/outputDelta',
 'item/fileChange/patchUpdated',
 'serverRequest/resolved',
 'item/mcpToolCall/progress',
 'mcpServer/oauthLogin/completed',
 'mcpServer/startupStatus/updated',
 'mcpServer/event/stream/notification',
 'account/updated',
 'account/gatewayOAuth/changed',
 'account/rateLimits/updated',
 'app/list/updated',
 'remoteControl/status/changed',
 'externalAgentConfig/import/progress',
 'externalAgentConfig/import/completed',
 'fs/changed',
 'item/reasoning/summaryTextDelta',
 'item/reasoning/summaryPartAdded',
 'item/reasoning/textDelta',
 'thread/compacted',
 'model/rerouted',
 'model/verification',
 'modelProvider/authRecoveryStarted',
 'modelProvider/authRecoveryCompleted',
 'turn/moderationMetadata',
 'model/safetyBuffering/updated',
 'warning',
 'guardianWarning',
 'deprecationNotice',
 'configWarning',
 'fuzzyFileSearch/sessionUpdated',
 'fuzzyFileSearch/sessionCompleted',
 'thread/realtime/started',
 'thread/realtime/itemAdded',
 'thread/realtime/item/started',
 'thread/realtime/item/transcript/delta',
 'thread/realtime/item/completed',
 'thread/realtime/transcript/delta',
 'thread/realtime/transcript/done',
 'thread/realtime/outputAudio/delta',
 'thread/realtime/sdp',
 'thread/realtime/error',
 'thread/realtime/closed',
 'windows/worldWritableWarning',
 'windowsSandbox/setupCompleted',
 'account/login/completed'))
DENIALS = {
    "item/commandExecution/requestApproval": {"decision": "cancel"},
    "item/fileChange/requestApproval": {"decision": "cancel"},
    "item/permissions/requestApproval": {"permissions": {}, "scope": "turn"},
    "execCommandApproval": {"decision": "abort"},
    "applyPatchApproval": {"decision": "abort"},
}


class TransportError(RuntimeError):
    """Fixed diagnostic code only; never embeds peer payloads or OS errors."""
    def __init__(self, code):
        self.code = code
        super().__init__(code)


@dataclass(frozen=True)
class Limits:
    timeout: float = 10.0
    close_timeout: float = 0.2
    line_bytes: int = 1_048_576
    total_bytes: int = 8_388_608
    messages: int = 4096
    outbound_bytes: int = 1_048_576
    notifications: int = 256

    def __post_init__(self):
        for name in ("timeout", "close_timeout"):
            value = getattr(self, name)
            if type(value) not in (int, float) or not math.isfinite(value) or value <= 0:
                raise ValueError("invalid_limits")
        for name in ("line_bytes", "total_bytes", "messages", "outbound_bytes", "notifications"):
            if type(getattr(self, name)) is not int or getattr(self, name) <= 0:
                raise ValueError("invalid_limits")


def _pairs(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate_key")
        result[key] = value
    return result


def _constant(value):
    raise ValueError("nonfinite")


def _float(value):
    result = float(value)
    if not math.isfinite(result):
        raise ValueError("nonfinite")
    return result


def _id(value):
    return type(value) is int and 0 <= value <= 2**63 - 1 or type(value) is str and 0 < len(value) <= 256


class Session:
    """Single-threaded POSIX session. Supply already-authorized host process inputs.

    fixed_tool and tool_callback must be supplied together. The callback receives
    one validated tool-call envelope's params; tool name is checked before it is
    invoked. It must validate arguments, thread/turn identity and authority before
    any effect. Only text tool responses are supported by this narrow primitive.
    """
    def __init__(self, argv, *, cwd, env, limits=None, fixed_tool=None, tool_callback=None):
        if os.name != "posix":
            raise ValueError("unsupported_pipe_selector_host")
        if (not isinstance(argv, (tuple, list)) or not argv or
                any(type(x) is not str or not x or "\0" in x for x in argv) or
                type(cwd) is not str or not os.path.isabs(cwd) or
                type(env) is not dict or any(type(k) is not str or type(v) is not str for k,v in env.items())):
            raise ValueError("invalid_host_inputs")
        if (fixed_tool is None) != (tool_callback is None) or (fixed_tool is not None and
                (type(fixed_tool) is not str or not fixed_tool or not callable(tool_callback))):
            raise ValueError("invalid_fixed_tool")
        self.limits = limits or Limits()
        if type(self.limits) is not Limits:
            raise ValueError("invalid_limits")
        self.fixed_tool, self.tool_callback = fixed_tool, tool_callback
        self.unknown = False
        self.closed = False
        self.initialized = False
        self._next_id = 1
        self._server_ids = set()
        self._tool_calls = set()
        self._buffer = bytearray()
        self._total = self._messages = 0
        self._notifications = deque()
        try:
            self.process = subprocess.Popen(tuple(argv), cwd=cwd, env=dict(env),
                stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                shell=False, bufsize=0)
        except (OSError, ValueError):
            raise TransportError("launch_failed") from None
        try:
            os.set_blocking(self.process.stdout.fileno(), False)
            os.set_blocking(self.process.stdin.fileno(), False)
        except OSError:
            self.unknown = True
            self.close()
            raise TransportError("launch_setup_failed") from None

    def _fail(self, code):
        self.unknown = True
        raise TransportError(code) from None

    def _ready(self):
        if self.closed or self.unknown:
            raise TransportError("session_unavailable")

    def _deadline(self):
        return time.monotonic() + self.limits.timeout

    def _select(self, stream, event, deadline):
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            self._fail("timeout")
        try:
            with selectors.DefaultSelector() as selector:
                selector.register(stream, event)
                if not selector.select(remaining):
                    self._fail("timeout")
        except (OSError, ValueError):
            self._fail("io_failed")

    def _send(self, message, deadline):
        try:
            data = (json.dumps(message, ensure_ascii=True, allow_nan=False,
                separators=(",", ":")) + "\n").encode("utf-8")
        except (ValueError, TypeError, RecursionError):
            self._fail("invalid_outbound")
        if len(data) > self.limits.outbound_bytes:
            self._fail("outbound_limit")
        offset = 0
        while offset < len(data):
            self._select(self.process.stdin, selectors.EVENT_WRITE, deadline)
            try:
                count = os.write(self.process.stdin.fileno(), data[offset:offset+65536])
                if count <= 0:
                    self._fail("write_failed")
                offset += count
            except BlockingIOError:
                continue
            except OSError:
                self._fail("write_failed")

    def _read(self, deadline):
        while True:
            if time.monotonic() >= deadline:
                self._fail("timeout")
            newline = self._buffer.find(b"\n")
            if newline >= 0:
                if newline > self.limits.line_bytes:
                    self._fail("line_limit")
                raw = bytes(self._buffer[:newline])
                del self._buffer[:newline+1]
                self._messages += 1
                if self._messages > self.limits.messages:
                    self._fail("message_limit")
                try:
                    value = json.loads(raw.decode("utf-8"), object_pairs_hook=_pairs,
                        parse_constant=_constant, parse_float=_float)
                except (ValueError, UnicodeError, RecursionError):
                    self._fail("invalid_json")
                if type(value) is not dict:
                    self._fail("invalid_envelope")
                return value
            if len(self._buffer) > self.limits.line_bytes:
                self._fail("line_limit")
            self._select(self.process.stdout, selectors.EVENT_READ, deadline)
            try:
                chunk = os.read(self.process.stdout.fileno(), min(65536,
                    self.limits.line_bytes + 1 - len(self._buffer)))
            except BlockingIOError:
                continue
            except OSError:
                self._fail("read_failed")
            if not chunk:
                self._fail("partial_eof" if self._buffer else "eof")
            self._total += len(chunk)
            if self._total > self.limits.total_bytes:
                self._fail("total_limit")
            self._buffer.extend(chunk)

    def _dispatch(self, message, expected_id, deadline):
        if "method" not in message:
            if (set(message) not in ({"id", "result"}, {"id", "error"}) or
                    not _id(message.get("id")) or type(message["id"]) is not int or
                    message["id"] != expected_id):
                self._fail("uncorrelated_response")
            if "error" in message:
                error = message["error"]
                if (type(error) is not dict or not {"code", "message"} <= set(error) or
                        not set(error) <= {"code", "message", "data"} or
                        type(error["code"]) is not int or type(error["message"]) is not str):
                    self._fail("invalid_error")
                self._fail("remote_error")
            if type(message["result"]) is not dict:
                self._fail("invalid_result")
            return True, message["result"]
        if "emittedAtMs" in message:
            # Public native transport adds optional notification emission metadata.
            if "id" in message or type(message["emittedAtMs"]) is not int or message["emittedAtMs"] < 0:
                self._fail("invalid_envelope")
            message = {k: v for k, v in message.items() if k != "emittedAtMs"}
        if (type(message["method"]) is not str or type(message.get("params")) is not dict or
                set(message) not in ({"method", "params"}, {"id", "method", "params"})):
            self._fail("invalid_envelope")
        method, params = message["method"], message["params"]
        if "id" not in message:
            if method not in NOTIFICATION_METHODS:
                self._fail("unknown_notification")
            if len(self._notifications) >= self.limits.notifications:
                self._fail("notification_limit")
            self._notifications.append(message)
            return False, None
        server_id = message["id"]
        if not _id(server_id):
            self._fail("invalid_server_id")
        identity = (type(server_id), server_id)
        if identity in self._server_ids:
            self._fail("duplicate_server_id")
        self._server_ids.add(identity)
        if method in DENIALS:
            self._send({"id": server_id, "result": DENIALS[method]}, deadline)
            self._fail("approval_denied")
        if method != "item/tool/call" or self.tool_callback is None or not self.initialized:
            self._fail("unexpected_server_request")
        required = {"arguments", "callId", "threadId", "tool", "turnId"}
        if (not required <= set(params) or not set(params) <= required | {"namespace"} or
                any(type(params[k]) is not str or not params[k] for k in required - {"arguments"}) or
                params["tool"] != self.fixed_tool or params.get("namespace") is not None):
            self._fail("invalid_tool_call")
        call_id = (params["threadId"], params["turnId"], params["callId"])
        if call_id in self._tool_calls:
            self._fail("duplicate_tool_call")
        self._tool_calls.add(call_id)
        try:
            result = self.tool_callback(params)
        except BaseException:
            self._fail("callback_failed")
        if time.monotonic() >= deadline:
            self._fail("callback_timeout")
        if (type(result) is not dict or set(result) != {"contentItems", "success"} or
                type(result["success"]) is not bool or type(result["contentItems"]) is not list or
                any(type(x) is not dict or set(x) != {"type", "text"} or x["type"] != "inputText" or
                    type(x["text"]) is not str for x in result["contentItems"])):
            self._fail("invalid_tool_result")
        self._send({"id": server_id, "result": result}, deadline)
        return False, None

    def _drain_available(self, deadline):
        # Observe already-arrived invalid/duplicate replies before another send.
        # A partial frame is uncertainty: await its bounded completion, never send
        # the next operation while that incomplete frame is pending.
        while True:
            if not self._buffer:
                try:
                    with selectors.DefaultSelector() as selector:
                        selector.register(self.process.stdout, selectors.EVENT_READ)
                        if not selector.select(0):
                            return
                except (OSError, ValueError):
                    self._fail("io_failed")
            self._dispatch(self._read(deadline), None, deadline)

    def request(self, method, params):
        self._ready()
        if type(method) is not str or method not in CLIENT_METHODS or type(params) is not dict:
            raise TransportError("method_not_allowed")
        if method == "initialize":
            if self.initialized or self._next_id != 1:
                raise TransportError("already_initialized")
            if self.fixed_tool is not None and (type(params.get("capabilities")) is not dict or
                    params["capabilities"].get("experimentalApi") is not True):
                raise TransportError("experimental_api_required")
        elif not self.initialized:
            raise TransportError("initialize_required")
        # account/read must never request implicit auth refresh.
        if method == "account/read" and params.get("refreshToken") is not False:
            raise TransportError("auth_refresh_not_allowed")
        deadline = self._deadline()
        self._drain_available(deadline)
        request_id = self._next_id
        self._next_id += 1
        self._send({"id": request_id, "method": method, "params": params}, deadline)
        while True:
            done, result = self._dispatch(self._read(deadline), request_id, deadline)
            if done:
                if method == "initialize":
                    self._send({"method": "initialized"}, deadline)
                    self.initialized = True
                return result

    def notification(self):
        """Read one known notification or service one fixed-tool call, bounded.

        Unsolicited responses fail closed. The caller owns payload validation and
        task completion criteria; a notification name never proves completion.
        """
        self._ready()
        if not self.initialized:
            raise TransportError("initialize_required")
        deadline = self._deadline()
        while not self._notifications:
            self._dispatch(self._read(deadline), None, deadline)
        return self._notifications.popleft()

    def close(self):
        """Return direct-child observation; never signal or claim descendant stop."""
        if not self.closed:
            self.closed = True
            for stream in (self.process.stdin, self.process.stdout):
                try:
                    stream.close()
                except OSError:
                    self.unknown = True
        try:
            code = self.process.wait(timeout=self.limits.close_timeout)
        except subprocess.TimeoutExpired:
            self.unknown = True
            return {"protocol": "unknown", "direct_child": "unknown", "descendants": "unknown"}
        return {"protocol": "unknown" if self.unknown else "observed",
            "direct_child": "exited", "exit_code": code, "descendants": "unknown"}
